name: Pull request CI

on:
  pull_request:
    types: [
        # Default pull_request trigger types.
        opened,
        synchronize,
        reopened,
      ]

jobs:
  lint_and_fast_tests:
    name: 'Run CLI tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          clean: 'false'
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v2
      - name: Install
        run: bun install --frozen-lockfile
      - name: Lint
        run: bun run lint
      - name: Build
        run: bun run build
      - name: Setup git
        run: git config --global user.email "test@gmail.com" && git config --global user.name "test"
      - name: Git Version
        run: git --version
      - name: Test
        run: bun run test-ci
