name: Pull request CI

on:
  pull_request:
    types: [
        # Default pull_request trigger types.
        opened,
        synchronize,
        reopened,
      ]

jobs:
  lint_and_fast_tests:
    name: 'Run CLI tests'
    runs-on: ubuntu-latest
    steps:
      # Basic setup
      - uses: actions/checkout@v2
        with:
          clean: 'false'
          fetch-depth: 0
      - uses: actions/setup-node@v3
      - name: Install
        run: yarn install --immutable
      - name: Lint
        run: yarn workspace @danerwilliams/charcoal run lint
      - name: Build
        run: yarn turbo run build
      - name: Setup git
        run: git config --global user.email "test@gmail.com" && git config --global user.name "test"
      - name: Git Version
        run: git --version
      - name: Test
        run: yarn workspace @danerwilliams/charcoal run test-ci
