name: Push CI
permissions:
  contents: write
on:
  push:
    branches: [main]
    tags:
      - "v*"

jobs:
  lint_and_fast_tests:
    name: "Run CLI tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          clean: "false"
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v2
      - name: Install
        run: bun install --frozen-lockfile
      - name: Build
        run: bun run build
      - name: Setup git
        run: git config --global user.email "test@gmail.com" && git config --global user.name "test"
      - name: Git Version
        run: git --version
      - name: Test
        run: bun run test-ci

  superlinter:
    name: "Run superlinter"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        continue-on-error: true
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TYPESCRIPT_DEFAULT_STYLE: prettier

  create-binaries:
    name: Upload executable binaries
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: bun-darwin-x64
            artifact-name: pk-macos-x64
          - os: macos-latest
            target: bun-darwin-arm64
            artifact-name: pk-macos-arm64
          - os: ubuntu-latest
            target: bun-linux-x64
            artifact-name: pk-linux-x64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Install
        run: bun install --frozen-lockfile
      - name: Build binary
        run: bun build ./apps/cli/src/index.ts --compile --outfile ${{ matrix.artifact-name }} --target ${{ matrix.target }}
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}-${{ github.sha }}
          path: ${{ matrix.artifact-name }}

  release:
    name: Release version
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [lint_and_fast_tests, create-binaries]
    runs-on: ubuntu-latest
    steps:
      - name: Download mac x64
        uses: actions/download-artifact@v4
        with:
          name: pk-macos-x64-${{ github.sha }}
      - name: Download mac arm64
        uses: actions/download-artifact@v4
        with:
          name: pk-macos-arm64-${{ github.sha }}
      - name: Download linux
        uses: actions/download-artifact@v4
        with:
          name: pk-linux-x64-${{ github.sha }}
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "pk-macos-x64,pk-macos-arm64,pk-linux-x64"
          draft: false
          prerelease: true
          allowUpdates: true
